name: JMeter Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Download Apache JMeter
      run: |
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xf apache-jmeter-5.6.3.tgz
        export JMETER_HOME=$PWD/apache-jmeter-5.6.3/bin

    - name: Run JMeter Test
      run: |
        ${JMETER_HOME}/jmeter -n -t "perf_actions/IP_Script.jmx" -l test_results.jtl -j jmeter.log

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-results
        path: test_results.jtl

    - name: Upload Logs
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-logs
        path: jmeter.log
